stage 2 development of get the value

diff --git a/conf/core b/conf/core
--- a/conf/core
+++ b/conf/core
@@ -39,6 +39,17 @@ ECHO_DEBUG()
     echo -e "${_DEBUG_FLAG} $@" >> ${INSTALL_LOG}
 }
 
+read_setting()
+{
+    answer="${1}"
+    if [ ! -z "${answer}" ]; then
+        ANSWER="${answer}"
+        echo ${ANSWER}
+    else
+        read ANSWER
+    fi
+}
+
 backup_file()
 {
     # Usage: backup_file file1 [file2 file3 ... fileN]
@@ -52,4 +63,215 @@ backup_file()
             fi
         done
     fi
+}
+
+check_user()
+{
+    # Check special user privilege to execute this script.
+    if [ X"$(id -u)" != X"$(id -u ${1})" ]; then
+        ECHO_ERROR "Please run this script as user: ${1}."
+        exit 255
+    else
+        if [ X"$(id -u)" == X"0" ]; then
+            export PATH="/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
+        else
+            :
+        fi
+    fi
+}
+
+check_pkg() {
+    # Usage: check_pkg <command> <package>
+    # It means: <package> owns <command>
+    cmd="$1"
+    pkg="$2"
+
+    for i in $(echo $PATH|sed 's/:/ /g'); do
+        [ -x $i/${cmd} ] && export HAS_CMD='YES' && break
+    done
+
+    if [ X"${HAS_CMD}" != X'YES' ]; then
+        export MISSING_PKGS="${MISSING_PKGS} ${pkg}"
+    fi
+
+    unset HAS_CMD
+}
+
+install_missing_pkg() {
+    if [ X"${MISSING_PKGS}" != X"" ]; then
+        eval ${install_pkg} ${MISSING_PKGS}
+        if [ X"$?" != X"0" ]; then
+            ECHO_ERROR "Please install missing package(s) ${MISSING_PKGS} first." && exit 255
+        fi
+    fi
+}
+
+check_runtime_dir() {
+    [ -d ${RUNTIME_DIR} ] || mkdir -p ${RUNTIME_DIR}
+
+    # Cleanup
+    rm -f ${RUNTIME_DIR}/.pkg_install_failed &>/dev/null
+}
+
+
+# Check necessery privileges/files/dirs.
+check_env()
+{
+    check_runtime_dir
+
+    # Check user privilege.
+    check_user root
+
+    # Check config tool: dialog.
+    check_pkg ${BIN_DIALOG} ${PKG_DIALOG}
+
+    # Check unzip & zip 
+    check_pkg ${BIN_ZIP} ${PKG_ZIP} 
+    check_pkg ${BIN_UNZIP} ${PKG_UNZIP}
+    check_pkg ${BIN_CURL} ${BIN_CURL}
+
+    ECHO_INFO -n "Checking configuration file: ${SERVER_CONFIG_FILE} ..."
+    if [ -f ${SERVER_CONFIG_FILE} ]; then
+        if grep '^#EOF$' ${SERVER_CONFIG_FILE} >/dev/null; then
+            echo -e " [FOUND]"
+            ECHO_QUESTION -n "Use it for server setting? [y|N]"
+            read_setting ${AUTO_USE_EXISTING_CONFIG_FILE}
+            case ${ANSWER} in
+                Y|y|[Yy][Ee][Ss] )
+                    ECHO_INFO "Use config file: ${SERVER_CONFIG_FILE} for server setting."
+                    . ${SERVER_CONFIG_FILE}
+
+                    # Check installation status.
+                    # After each component installation was completed, there
+                    # should be a variable in ${STATUS_FILE}, e.g.
+                    #
+                    #   export STATUS_APACHE_INSTALLATION='DONE'
+                    #   export STATUS_APACHE_CONFIGURATION='DONE'
+                    #
+                    if [ -f ${STATUS_FILE} ]; then
+                        ECHO_INFO "Import installation process status from file: ${STATUS_FILE}."
+                        . ${STATUS_FILE}
+                    else
+                        echo '' > ${STATUS_FILE}
+                    fi
+
+                    # Initialize tip file.
+                    if [ ! -f ${TIP_FILE} ]; then
+                        cat > ${TIP_FILE} <<EOF
+${CONF_MSG}
+EOF
+
+                        chown ${SYS_USER_ROOT}:${SYS_GROUP_ROOT} ${TIP_FILE}
+                        chmod 0400 ${TIP_FILE}
+                    fi
+                    ;;
+                N|n|* )
+                    ECHO_INFO "Skip configuration file: ${SERVER_CONFIG_FILE}."
+                    backup_file ${SERVER_CONFIG_FILE}
+                    . ${CONFIG_VIA_DIALOG}
+                    ;;
+            esac
+        else
+            ECHO_INFO "Found, but not finished. Launching installation wizard."
+            . ${CONFIG_VIA_DIALOG}
+        fi
+    else
+        ECHO_INFO "NOT FOUND. Launching installation wizard."
+        . ${CONFIG_VIA_DIALOG}
+    fi
+}
+
+check_status_before_run()
+{
+    # If function was successfully executed, this function will write one line
+    # in $STATUS_FILE:
+    #
+    #   export status_[function_name]='DONE'
+    #
+    function_name="${1}"
+    function_status_name="status_${function_name}"
+    function_status_value="$(eval echo \$${function_status_name})"
+    if [ X"${function_status_value}" == X"DONE" ]; then
+        ECHO_SKIP "Function: $1."
+    else
+        $function_name
+    fi
+}
+
+generate_password_hash()
+{
+    _scheme="${1}"
+    _password="${2}"
+
+    if [ X"${_scheme}" == X'BCRYPT' ]; then
+        _scheme='BLF-CRYPT'
+    fi
+
+    doveadm pw -s "${_scheme}" -p "${_password}"
+}
+
+# Install/Remove binary packages on Debian/Ubuntu.
+install_pkg_debian()
+{
+    ECHO_INFO "Installing package(s): $@"
+    ${APTGET} install -y $@
+
+    # Leave a mark if package installation failed.
+    if [ X"$?" != X"0" ]; then
+        echo '' > ${RUNTIME_DIR}/.pkg_install_failed
+    fi
+}
+
+remove_pkg_debian()
+{
+    ECHO_INFO "Removing package(s): $@"
+    ${APTGET} purge -y $@
+    if [ X"$?" != X"0" ]; then
+        ECHO_ERROR "Package removed failed, please check the terminal output."
+        echo '' > ${RUNTIME_DIR}/.pkg_remove_failed
+    fi
+}
+
+ask_confirm()
+{
+    # Usage: ask_confirm 'prompt text'
+    prompt_text="${1}"
+    echo -ne "${prompt_text} [y|N]"
+    read ANSWER
+    case ${ANSWER} in
+        Y|y ) : ;;
+        N|n|* ) echo "Exit." && exit ;;
+    esac
+}
+
+update_sysctl_param()
+{
+    export _param="$1"
+    export _value="$2"
+
+    if grep "^${_param}\>" ${SYSCTL_CONF} &>/dev/null; then
+        # param exists, updating it.
+        perl -pi -e 's#^($ENV{_param})[ =].*#${1}=$ENV{_value}#' ${SYSCTL_CONF}
+    else
+        # param doesn't exist. add a new one.
+        echo "${_param}=${_value}" >> ${SYSCTL_CONF}
+    fi
+
+    unset _param _value
+}
+
+write_server_kv()
+{
+    # usage: write_server_kv <param> <value>
+    # Storage value to file /root/.server/kv/<param>.
+    param="$1"
+    value="$2"
+
+    [[ -f ${SERVER_KV_DIR} ]] || mkdir -p ${SERVER_KV_DIR}
+
+    f="${SERVER_KV_DIR}/${param}"
+    echo "${value}" > ${f}
+
+    chown -R ${SYS_USER_ROOT}:${SYS_GROUP_ROOT} ${SERVER_KV_DIR}
+    chmod -R 0400 ${SERVER_KV_DIR}
 }
diff --git a/conf/global b/conf/global
--- a/conf/global
+++ b/conf/global
@@ -2,6 +2,31 @@
 
 export DATE="$(/bin/date +%Y.%m.%d.%H.%M.%S)"
 
+# For perl and run-time locale setting.
+export LC_ALL=C
+export LC_CTYPE=C
+export LANG=C
+
+# Tells ncurses (dialog) to use Unicode values which correspond to the VT100
+# line-drawing glyphs.
+export NCURSES_NO_UTF8_ACS=1
+
+# Debug mode: YES, NO.
+export SERVER_DEBUG="${SERVER_DEBUG:=NO}"
+
+# Tools.
+export CONFIG_VIA_DIALOG="${DIALOG_DIR}/config_via_dialog.sh"
+# Note: config file will be sourced in file 'conf/core', function 'check_env()'.
+export SERVER_CONFIG_FILE="${ROOTDIR}/config"
+export TIP_FILE="${ROOTDIR}/server.tips"
+export DB_TIP_FILE="${ROOTDIR}/DB_details.tips"
+export Developer_TIP_FILE="${ROOTDIR}/For_developers.tips"
+export STATUS_FILE="${RUNTIME_DIR}/install.status"
+export INSTALL_LOG="${RUNTIME_DIR}/install.log"
+export PKG_INSTALL_LOG="${RUNTIME_DIR}/pkg.install.log"
+# Directory used to store kv files (one value in one file).
+export SERVER_KV_DIR='/root/.server/kv'
+
 # Output flag.
 export _INFO_FLAG="[ INFO ]"
 export _SKIP_FLAG="< SKIP >"
@@ -10,26 +35,163 @@ export _QUESTION_FLAG="< Question >"
 export _BACKUP_FLAG=" + < Backup >"
 export _DEBUG_FLAG=" + < DEBUG >"
 
+export CONF_MSG="#
+# File generated by linux administrator at maticz technologies:
+#
+# url: https://www.maticz.com
+#
+"
+
+# Kernel name, in upper cases.
+export KERNEL_NAME="$(uname -s | tr '[a-z]' '[A-Z]')"
+
 # Command used to genrate a random string.
 # Usage: str="$(${RANDOM_STRING})"
 export RANDOM_STRING='eval </dev/urandom tr -dc A-Za-z | (head -c $1 &>/dev/null || head -c 6)' 
 export RANDOM_NUMBER='shuf -i 49152-65535 -n 1'
 
+# command: dialog.
+export BIN_DIALOG="dialog"
+export PKG_DIALOG="dialog"
+
+# command: zip , unzip, curl.
+export BIN_ZIP='zip'
+export PKG_ZIP='zip'
+export BIN_UNZIP='unzip'
+export PKG_UNZIP='unzip'
+export BIN_CURL='curl'
+export PKG_CURL='curl'
+
+# Shells
+export SHELL_NOLOGIN='/sbin/nologin'
+export SHELL_BASH='/bin/bash'
+
+# Default password scheme for SQL backends.
+# LDAP backend will use SSHA instead (defined in dialog/config_via_dialog.sh)
+# for easier third-party application integrations.
+export DEFAULT_PASSWORD_SCHEME='SSHA512'
+
+# Check distribution.
+#   - DISTRO
+#   - DISTRO_VERSION
+#   - DISTRO_CODENAME
+#
+# UNSUPPORTED_RELEASE will be set to 'YES' if current Linux/BSD release is
+# an old release and unsupported anymore.
+export UNSUPPORTED_RELEASE='NO'
+
+
+# Detect distro name and release version.
+if [ X"${KERNEL_NAME}" == X'LINUX' ]; then
+    export DISTRO_VERSION=$(awk -F'"' '/^VERSION_ID=/ {print $2}' /etc/os-release)
+
+    # Debian:
+    #   - 11: bullseye
+    # Ubuntu:
+    #   - 18.04: Bionic Beaver
+    #   - 20.04: focal
+    #   - 22.04: jammy
+    export DISTRO_CODENAME=$(awk -F'=' '/^VERSION_CODENAME=/ {print $2}' /etc/os-release)
+
+    # Directory of RC scripts.
+    export DIR_RC_SCRIPTS='/etc/init.d'
+
+    if [ -f /etc/lsb-release ] && grep -i 'DISTRIB_ID=Ubuntu' /etc/lsb-release &>/dev/null; then
+        # Ubuntu
+        export DISTRO='UBUNTU'
+
+        # Supported releases: 18.04, 20.04, 22.04.
+        if echo "${DISTRO_VERSION}" | grep -E '^(16|17|19\.|21\.|20\.10)' &>/dev/null ; then
+            export UNSUPPORTED_RELEASE='YES'
+        fi
+    else
+        export UNSUPPORTED_RELEASE='YES'
+    fi
+else
+    # Not support *BSD and other distrobutions yet.
+    echo "Error: Your OS is not supported yet."
+    exit 255
+fi
+
+# Exit and prompt to use a supported Linux/BSD distribution
+if [ X"${UNSUPPORTED_RELEASE}" == X'YES' ]; then
+    cat <<EOF
+********* ERROR *********
+Release version of the operating system on this server is unsupported by
+iRedMail, please access below link to get the latest iRedMail and a list
+of supported Linux/BSD distributions and release versions.
+
+http://www.iredmail.org/download.html
+
+*************************
+EOF
+
+    exit 255
+fi
+
 # root user/group name. Note: not all OSes have group 'root'.
 export SYS_USER_ROOT='root'
 export SYS_GROUP_ROOT='root'
 
-# Backup script file names.
-export BACKUP_SCRIPT_MONGO_NAME='backup_mongo.sh'
+# Check processor type.
+if [ X"${DISTRO}" == X'DEBIAN' ]; then
+    arch="$(uname -m)"
+else
+    arch="$(uname -p)"
+fi
+case $arch in
+    i[3456]86) export OS_ARCH='i386' ;;
+    x86_64|amd64) export OS_ARCH='x86_64' ;;
+    *) export OS_ARCH="${arch}" ;;
+esac
+
+
+# install_pkg: function used to install packages without confirm.
+# remove_pkg: function used to remove packages without confirm.
+# LIST_ALL_PKGS: command used to list all installed packages.
+# LIST_FILES_IN_PKG: command used to list files installed by special package.
+  # Ubuntu & Debian.
+    export DEBIAN_FRONTEND='noninteractive'
+    export SHELL_NOLOGIN='/usr/sbin/nologin'
+
+    # Package management.
+    if [ X"${APTGET}" != X"" ]; then
+        export APTGET="${APTGET}"
+    else
+        # "WARNING: apt does not have a stable CLI interface. Use with caution in scripts."
+        export APTGET='apt-get'
+    fi
+
+    # Package management.
+    export install_pkg='install_pkg_debian'
+    export remove_pkg='remove_pkg_debian'
+    export LIST_ALL_PKGS="dpkg -l |awk '{print $2}'"
+    export LIST_FILES_IN_PKG='dpkg -L'
+
+    # SSHD log file
+    export SSHD_LOGFILE='/var/log/auth.log'
+
+    # Crontab related.
+    export CRON_SPOOL_DIR='/var/spool/cron/crontabs'
+
+    # Directory /etc/default/ on Debian/Ubuntu.
+    export ETC_SYSCONFIG_DIR='/etc/default'
+
+    export USE_NFTABLES='YES'
+    export NFTABLES_CONF='/etc/nftables.conf'
+    export FIREWALL_RULE_CONF="${NFTABLES_CONF}"
+
+    # Directory used to store SSL/TLS key/cert file.
+    export SSL_FILE_DIR="/etc/ssl"
+
+    # `python3` is a symbol link to `python3X`.
+    export UWSGI_PY3_PLUGIN_NAME='python3'
+
+
 
 # Cache clear scirpt file names.
 export BUFFER_CACHE_CLEAR='clearcache.sh'
 
-export DB_TIP_FILE="${ROOTDIR}/DB_details.tips"
-export Developer_TIP_FILE="${ROOTDIR}/For_developers.tips"
-export STATUS_FILE="${RUNTIME_DIR}/install.status"
-export INSTALL_LOG="${RUNTIME_DIR}/install.log"
-export PKG_INSTALL_LOG="${RUNTIME_DIR}/pkg.install.log"
 
 # Shells
 export SHELL_NOLOGIN='/sbin/nologin'
@@ -40,3 +202,31 @@ export CRON_SPOOL_DIR='/var/spool/cron/crontabs'
 
 # Root's cron file
 export CRON_FILE_ROOT="${CRON_SPOOL_DIR}/${SYS_USER_ROOT}"
+
+# Location of sshd_config
+export SSHD_CONFIG='/etc/ssh/sshd_config'
+
+if [[ -f ${SSHD_CONFIG} ]]; then
+    export SSHD_PORT="$(awk '/^Port/ {print $2}' ${SSHD_CONFIG} | head -1)"
+    export SSHD_PORT2="$(awk '/^Port/ {print $2}' ${SSHD_CONFIG} | tail -1)"
+fi
+
+if [ X"${SSHD_PORT}" == X'' ]; then
+    # No port number defined, use default port number (22).
+    export SSHD_PORT='22'
+    export SSHD_PORT2='22'
+fi
+
+export SSHD_PORTS_WITH_COMMA="${SSHD_PORT}"
+export SSHD_PORTS_WITH_SPACE="${SSHD_PORT}"
+
+if [ X"${SSHD_PORT}" != X'' -a X"${SSHD_PORT2}" != X'' -a X"${SSHD_PORT}" != X"${SSHD_PORT2}" ]; then
+    export SSHD_PORTS_WITH_COMMA="${SSHD_PORT},${SSHD_PORT2}"
+    export SSHD_PORTS_WITH_SPACE="${SSHD_PORT} ${SSHD_PORT2}"
+fi
+
+# sysctl.conf
+export SYSCTL_CONF='/etc/sysctl.conf'
+
+# Backup script file names.
+export BACKUP_SCRIPT_MONGO_NAME='backup_mongo.sh'
